org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
minecraft_version=1.20.1
forge_version=47.4.9
forge_version_range=[47,)
loader_version_range=[1,)

mod_id=fasttag
mod_name=Fast Tag
mod_license=GNU LGPL 3.0
mod_version=1.20-26.1-forge
mod_group_id=fast
mod_authors=nutant233
mod_description=Optimize performance related to tags.
